# Generated by Django 5.2.8 on 2025-11-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1000, unique=True)),
                ('file_name', models.CharField(max_length=500)),
                ('collection_name', models.CharField(help_text='Source collection/folder', max_length=200)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('num_pages', models.IntegerField(blank=True, null=True)),
                ('num_chunks', models.IntegerField(default=0, help_text='Number of text chunks created')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['file_path'], name='core_docume_file_pa_e7bd6c_idx'), models.Index(fields=['is_processed'], name='core_docume_is_proc_06ea89_idx')],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('metal_type', models.CharField(blank=True, max_length=200)),
                ('environment', models.CharField(blank=True, max_length=200)),
                ('temperature', models.CharField(blank=True, max_length=100)),
                ('num_results_retrieved', models.IntegerField(default=0)),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='core_queryl_created_53c018_idx')],
            },
        ),
    ]
